### ISSUE TITLE
Fix saving/opening documents with time in the uri in eXistDB

### ISSUE THREAD

**Issue by obujor** [cirsfid-unibo/lime-server#8]
As emerged in this [issue comment](https://github.com/cirsfid-unibo/lime/issues/70#issuecomment-395456455) there are some problems with saving and opening documents containing time in the version.
The problem is probably caused by **:** in the uri, figure out how eXistdb handles this character.

**Comment by eltorre** [comment]
Any estimate of when will this be fixed?

What are the drawbacks of disabling eXistdb?

Is it be possible to disable the "time" field of the version instead?

**Comment by obujor** [comment]
I don't know when it will be fixed.
By setting `existIsMainBackend` to false, existDb is still used but only for writing, LIME will use file system for reading and writing. One drawback is that if you change the documents with XQuery in eXistdb you cannot access them from LIME.
The time field is optional so you can ignore it by leaving the default value.

**Comment by obujor** [comment]
Thanks for the tip, the issue is not the XML itself because the character `:` is inserted in an attribute. The problem is about using this character in a resource name in eXist, there are some known [issues](https://github.com/eXist-db/exist/issues/1824) about special characters.

LIME doesn't trigger documents changing through XQuery, you can do this manually for different purposes i.e. normalizing some attributes, changing the ontology used in `<references>`, etc...

**Comment by obujor** [comment]
This is fixed now, you can save and open files with the time in the version. BUT I don't recommend you to use time in LIME because this feature is not well supported in the client, i.e. it's missing from the 'Metadata editor' and from the URI, so this information will not be included in the final AkomaNtoso.
